import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const projectRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const sourcePath = (...segments) => path.join(projectRoot, 'src', ...segments);

function makeClassicScript(source) {
  return source
    .replace(/^export\s+/gm, '')
    .replace(/^import[^;]+;\s*$/gm, '');
}

const [styles, markup, previewTemplate, data, calc, app] = await Promise.all([
  readFile(sourcePath('styles.css'), 'utf8'),
  readFile(sourcePath('markup.html'), 'utf8'),
  readFile(sourcePath('preview-template.html'), 'utf8'),
  readFile(sourcePath('data.js'), 'utf8'),
  readFile(sourcePath('calc.js'), 'utf8'),
  readFile(sourcePath('app.js'), 'utf8'),
]);

const runtime = [data, calc, app].map(makeClassicScript).join('\n\n');
const tildaBlock = `<!-- MBS Coffee Cost Calculator: generated by scripts/build.mjs -->\n<style>\n${styles}\n</style>\n\n${markup}\n\n<script>\n${runtime}\n</script>\n`;
const preview = previewTemplate
  .replace('/* APP_STYLES */', styles)
  .replace('<!-- APP_MARKUP -->', markup)
  .replace('/* APP_SCRIPT */', runtime);

await Promise.all([
  writeFile(path.join(projectRoot, 'tilda-block.html'), tildaBlock),
  writeFile(path.join(projectRoot, 'index.html'), preview),
]);

console.log('Built index.html and tilda-block.html');
