import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const projectRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const sourcePath = (...segments) => path.join(projectRoot, 'src', ...segments);

function makeClassicScript(source) {
  return source
    .replace(/^export\s+/gm, '')
    .replace(/^import[^;]+;\s*$/gm, '');
}

function makeTildaSeoBlock(markup, styles) {
  const heroEnd = markup.indexOf('\n\n  <section class="mbs-costcalc__tool"');
  const articleStart = markup.indexOf('\n\n  <section class="mbs-costcalc__how"');
  const dialogStart = markup.indexOf('\n\n  <dialog class="mbs-costcalc__dialog"');

  if (heroEnd === -1 || articleStart === -1 || dialogStart === -1) {
    throw new Error('Could not isolate the static SEO sections from markup.html');
  }

  const hero = markup
    .slice(0, heroEnd)
    .replace('data-mbs-costcalc-root', 'data-mbs-costcalc-seo');
  const article = markup.slice(articleStart, dialogStart);
  const staticMarkup = `${hero}\n\n  <div data-mbs-costcalc-loader-slot aria-live="polite"></div>${article}\n</main>`;

  return `<!-- MBS Coffee Cost Calculator: static SEO content for the first Tilda T123 block. Paste this file before tilda-loader.html. -->\n<style>\n${styles}\n</style>\n\n${staticMarkup}\n\n<script>\n(function () {\n  var root = document.querySelector('[data-mbs-costcalc-seo]');\n  if (!root || root.getAttribute('data-mbs-costcalc-seo-ready') === '1') return;\n  root.setAttribute('data-mbs-costcalc-seo-ready', '1');\n\n  var faqItems = Array.prototype.slice.call(root.querySelectorAll('.mbs-costcalc__faq details'));\n  faqItems.forEach(function (item) {\n    item.addEventListener('toggle', function () {\n      if (!item.open) return;\n      faqItems.forEach(function (otherItem) {\n        if (otherItem !== item) otherItem.removeAttribute('open');\n      });\n    });\n  });\n}());\n</script>\n`;
}

const [styles, markup, hostedMarkup, previewTemplate, data, calc, app] = await Promise.all([
  readFile(sourcePath('styles.css'), 'utf8'),
  readFile(sourcePath('markup.html'), 'utf8'),
  readFile(sourcePath('hosted-markup.html'), 'utf8'),
  readFile(sourcePath('preview-template.html'), 'utf8'),
  readFile(sourcePath('data.js'), 'utf8'),
  readFile(sourcePath('calc.js'), 'utf8'),
  readFile(sourcePath('app.js'), 'utf8'),
]);

const runtime = [data, calc, app].map(makeClassicScript).join('\n\n');
const tildaBlock = `<!-- MBS Coffee Cost Calculator: local full-page archive, generated by scripts/build.mjs. Do not paste into Tilda; use tilda-loader.html. -->\n<style>\n${styles}\n</style>\n\n${markup}\n\n<script>\n${runtime}\n</script>\n`;
const hostedPage = `<!-- MBS Coffee Cost Calculator: deploy to https://api.barista-school.ru/api/coffee-cost-calculator.html -->\n<style>\n${styles}\n</style>\n\n${hostedMarkup}\n\n<script>\n${runtime}\n</script>\n`;
const tildaSeoBlock = makeTildaSeoBlock(markup, styles);
const preview = previewTemplate
  .replace('/* APP_STYLES */', styles)
  .replace('<!-- APP_MARKUP -->', markup)
  .replace('/* APP_SCRIPT */', runtime);

await mkdir(path.join(projectRoot, 'hosted'), { recursive: true });

await Promise.all([
  writeFile(path.join(projectRoot, 'tilda-block.html'), tildaBlock),
  writeFile(path.join(projectRoot, 'tilda-seo-block.html'), tildaSeoBlock),
  writeFile(path.join(projectRoot, 'index.html'), preview),
  writeFile(path.join(projectRoot, 'hosted', 'coffee-cost-calculator.html'), hostedPage),
]);

console.log('Built index.html, tilda-seo-block.html, tilda-block.html and hosted/coffee-cost-calculator.html');
