import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const projectRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const sourcePath = (...segments) => path.join(projectRoot, 'src', ...segments);

function makeClassicScript(source) {
  return source
    .replace(/^export\s+/gm, '')
    .replace(/^import[^;]+;\s*$/gm, '');
}

const [styles, markup, hostedMarkup, previewTemplate, data, calc, app] = await Promise.all([
  readFile(sourcePath('styles.css'), 'utf8'),
  readFile(sourcePath('markup.html'), 'utf8'),
  readFile(sourcePath('hosted-markup.html'), 'utf8'),
  readFile(sourcePath('preview-template.html'), 'utf8'),
  readFile(sourcePath('data.js'), 'utf8'),
  readFile(sourcePath('calc.js'), 'utf8'),
  readFile(sourcePath('app.js'), 'utf8'),
]);

const runtime = [data, calc, app].map(makeClassicScript).join('\n\n');
const tildaBlock = `<!-- MBS Coffee Cost Calculator: local full-page archive, generated by scripts/build.mjs. Do not paste into Tilda; use tilda-loader.html. -->\n<style>\n${styles}\n</style>\n\n${markup}\n\n<script>\n${runtime}\n</script>\n`;
const hostedPage = `<!-- MBS Coffee Cost Calculator: deploy to https://api.barista-school.ru/api/coffee-cost-calculator.html -->\n<style>\n${styles}\n</style>\n\n${hostedMarkup}\n\n<script>\n${runtime}\n</script>\n`;
const preview = previewTemplate
  .replace('/* APP_STYLES */', styles)
  .replace('<!-- APP_MARKUP -->', markup)
  .replace('/* APP_SCRIPT */', runtime);

await mkdir(path.join(projectRoot, 'hosted'), { recursive: true });

await Promise.all([
  writeFile(path.join(projectRoot, 'tilda-block.html'), tildaBlock),
  writeFile(path.join(projectRoot, 'index.html'), preview),
  writeFile(path.join(projectRoot, 'hosted', 'coffee-cost-calculator.html'), hostedPage),
]);

console.log('Built index.html, tilda-block.html and hosted/coffee-cost-calculator.html');
