// Публичный учебный снимок базовых рецептур Coffee Menu.
// Источник: Coffee_menu/HTML_coffee_menu, commit 1439df3527214f1190ccfb955b40b292c08719bb.

export const COST_CALCULATOR_SNAPSHOT = {
  schemaVersion: '1.0.0',
  capturedAt: '2026-07-30',
  source: {
    repository: 'Coffee_menu/HTML_coffee_menu',
    commit: '1439df3527214f1190ccfb955b40b292c08719bb',
    recipeFile: 'src/data/drinks.js',
    ingredientFile: 'src/data/mat.js',
  },
  ingredients: {
    coffee: {
      name: 'Зерно эспрессо',
      packageLabel: 'упаковка 1 кг',
      amountUnit: 'г',
      packageSizeUnit: 'г',
      defaultPrice: 2000,
      defaultSize: 1000,
    },
    filter_coffee: {
      name: 'Зерно под фильтр',
      packageLabel: 'упаковка 1 кг',
      amountUnit: 'г',
      packageSizeUnit: 'г',
      defaultPrice: 4000,
      defaultSize: 1000,
    },
    milk: {
      name: 'Молоко',
      packageLabel: 'упаковка 1 л',
      amountUnit: 'мл',
      packageSizeUnit: 'мл',
      defaultPrice: 130,
      defaultSize: 1000,
    },
    cream: {
      name: 'Сливки 10%',
      packageLabel: 'упаковка 1 л',
      amountUnit: 'мл',
      packageSizeUnit: 'мл',
      defaultPrice: 250,
      defaultSize: 1000,
    },
    cocoa: {
      name: 'Какао-порошок',
      packageLabel: 'упаковка 1 кг',
      amountUnit: 'г',
      packageSizeUnit: 'г',
      defaultPrice: 2500,
      defaultSize: 1000,
    },
    matcha: {
      name: 'Матча',
      packageLabel: 'упаковка 1 кг',
      amountUnit: 'г',
      packageSizeUnit: 'г',
      defaultPrice: 8000,
      defaultSize: 1000,
    },
    sugar: {
      name: 'Сахар',
      packageLabel: 'упаковка 1 кг',
      amountUnit: 'г',
      packageSizeUnit: 'г',
      defaultPrice: 56,
      defaultSize: 1000,
    },
    sugar_van: {
      name: 'Сахар ванильный',
      packageLabel: 'упаковка 1 кг',
      amountUnit: 'г',
      packageSizeUnit: 'г',
      defaultPrice: 140,
      defaultSize: 1000,
    },
    cup250: {
      name: 'Стакан 250 мл с крышкой',
      packageLabel: '1 штука',
      amountUnit: 'шт',
      packageSizeUnit: 'шт',
      defaultPrice: 9,
      defaultSize: 1,
    },
    cup350: {
      name: 'Стакан 350 мл с крышкой',
      packageLabel: '1 штука',
      amountUnit: 'шт',
      packageSizeUnit: 'шт',
      defaultPrice: 11,
      defaultSize: 1,
    },
    cup450: {
      name: 'Стакан 450 мл с крышкой',
      packageLabel: '1 штука',
      amountUnit: 'шт',
      packageSizeUnit: 'шт',
      defaultPrice: 13,
      defaultSize: 1,
    },
    cup_p300: {
      name: 'Пластиковый стакан 300 мл',
      packageLabel: '1 штука',
      amountUnit: 'шт',
      packageSizeUnit: 'шт',
      defaultPrice: 11,
      defaultSize: 1,
    },
  },
  recipes: [
    {
      id: 'espresso-doppio',
      category: 'Классика',
      name: 'Эспрессо доппио',
      volumeMl: 50,
      ingredients: [{ code: 'coffee', amount: 19 }, { code: 'cup250', amount: 1 }],
    },
    {
      id: 'americano-200',
      category: 'Классика',
      name: 'Американо',
      volumeMl: 200,
      ingredients: [{ code: 'coffee', amount: 19 }, { code: 'cup250', amount: 1 }],
    },
    {
      id: 'cappuccino-200',
      category: 'Молочные',
      name: 'Капучино',
      volumeMl: 200,
      ingredients: [{ code: 'coffee', amount: 19 }, { code: 'milk', amount: 170 }, { code: 'cup250', amount: 1 }],
    },
    {
      id: 'cappuccino-300',
      category: 'Молочные',
      name: 'Капучино',
      volumeMl: 300,
      ingredients: [{ code: 'coffee', amount: 19 }, { code: 'milk', amount: 250 }, { code: 'cup350', amount: 1 }],
    },
    {
      id: 'latte-300',
      category: 'Молочные',
      name: 'Латте',
      volumeMl: 300,
      ingredients: [{ code: 'coffee', amount: 19 }, { code: 'milk', amount: 250 }, { code: 'cup350', amount: 1 }],
    },
    {
      id: 'latte-400',
      category: 'Молочные',
      name: 'Латте',
      volumeMl: 400,
      ingredients: [{ code: 'coffee', amount: 19 }, { code: 'milk', amount: 350 }, { code: 'cup450', amount: 1 }],
    },
    {
      id: 'flat-white-200',
      category: 'Молочные',
      name: 'Флэт уайт',
      volumeMl: 200,
      ingredients: [{ code: 'coffee', amount: 19 }, { code: 'milk', amount: 170 }, { code: 'cup250', amount: 1 }],
    },
    {
      id: 'vanilla-raf-300',
      category: 'Особые',
      name: 'Раф ванильный',
      volumeMl: 300,
      ingredients: [{ code: 'coffee', amount: 19 }, { code: 'cream', amount: 250 }, { code: 'sugar_van', amount: 10 }, { code: 'cup350', amount: 1 }],
    },
    {
      id: 'cocoa-300',
      category: 'Особые',
      name: 'Какао',
      volumeMl: 300,
      ingredients: [{ code: 'milk', amount: 250 }, { code: 'cocoa', amount: 13 }, { code: 'sugar', amount: 10 }, { code: 'cup350', amount: 1 }],
    },
    {
      id: 'matcha-300',
      category: 'Особые',
      name: 'Матча',
      volumeMl: 300,
      ingredients: [{ code: 'matcha', amount: 3 }, { code: 'milk', amount: 250 }, { code: 'cup350', amount: 1 }],
    },
    {
      id: 'iced-latte-300',
      category: 'Холодные',
      name: 'Айс-латте',
      volumeMl: 300,
      ingredients: [{ code: 'coffee', amount: 19 }, { code: 'milk', amount: 200 }, { code: 'cup_p300', amount: 1 }],
    },
    {
      id: 'filter-coffee-300',
      category: 'Фильтр',
      name: 'Фильтр-кофе',
      volumeMl: 300,
      ingredients: [{ code: 'filter_coffee', amount: 20 }, { code: 'cup350', amount: 1 }],
    },
  ],
};

export const DEFAULT_RECIPE_ID = 'cappuccino-300';
